name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: friendlyanon/fetch-core-count@v1
        id: cores

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
        with:
          version: '1.10.2'

      - name: Configure
        run: cmake -S test -B build -G Ninja -D CMAKE_BUILD_TYPE=Release
          -D FULL_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Run
        working-directory: build
        run: ctest --output-on-failure -j ${{ steps.cores.outputs.plus_one }}
